name: medclip_eval
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0 # to match with pip's transformer's numpy dependency
  - pandas
  - pillow
  - requests
  - tqdm
  - nltk>=3.7
  - scikit-learn>=1.1.2
  - pytorch>=1.12.1
  - torchvision>=0.13.1
  - notebook
  - ipywidgets
  - matplotlib
  - seaborn
  - pip
  - pip:
    - wget
    - textaugment>=1.3.4
    - timm>=0.6.11
    - transformers>=4.23.1,<=4.24.0
    - kagglehub
